# -*- coding: utf-8 -*-
"""Energy efficiency LLM .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smJM_sKXTTSQ-rVBsqJLqIeIMtZoa_jv
"""

# %% [markdown]
# # Energy-to-Token Production: Measurement Pipeline v7
#
# ## Research Methodology
#
# Primary metric:
#
#     End-to-End Energy per Output Token
#
#     E_tok = total GPU energy / number of generated output tokens
#
# We intentionally DO NOT estimate decode energy by subtracting
# a separate 1-token generation from a full generation.
#
# Previous validation showed that differential prefill/decode estimation
# was not reliable at this workload scale:
#
#     R² = 0.7372
#     regression slope = negative
#
# Therefore, this version measures the complete inference request:
#
#     Prefill + Decode
#            ↓
#     Total GPU Energy
#            ↓
#     Total Output Tokens
#            ↓
#     Joules / Output Token
#
# Research Question:
#
# How do quantization precision, batch size, and context length jointly
# affect energy efficiency (J/token), latency, throughput, memory,
# GPU utilization, and model quality during LLM inference?
#
# Main Hypothesis:
#
# Quantization does not necessarily reduce energy consumption per output
# token. Its effect depends on precision level, batch size, and context
# length, and may be limited or reversed by dequantization overhead or
# hardware/kernel inefficiencies.
#
# Experimental factors:
#
# Precision:
#     FP16
#     INT8
#     INT4
#
# Batch:
#     1
#     8
#
# Context:
#     128 tokens
#     2048 tokens
#
# Total configurations:
#
#     3 × 2 × 2 = 12
#
# Primary metric:
#
#     J/output-token
#
# Secondary metrics:
#
#     tokens/s
#     request latency
#     peak GPU memory
#     average GPU utilization
#     quality accuracy
#
# Energy is measured using NVML GPU power samples integrated
# using the trapezoidal rule.

# %%
# ============================================================
# Cell 1: Install dependencies
# ============================================================

!pip install -q -U transformers accelerate "bitsandbytes>=0.46.1" pynvml scipy pandas matplotlib datasets

# %%
# ============================================================
# Cell 1b: Mount Google Drive + Hugging Face cache
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

import os

HF_CACHE = "/content/drive/MyDrive/hf_cache"
os.makedirs(HF_CACHE, exist_ok=True)

os.environ["HF_HOME"] = HF_CACHE

# Keep datasets cache LOCAL because Google Drive can cause
# file-locking problems with Hugging Face datasets.
DATASET_CACHE = "/content/hf_datasets_cache"
os.makedirs(DATASET_CACHE, exist_ok=True)

os.environ["HF_DATASETS_CACHE"] = DATASET_CACHE

print("Model cache:", HF_CACHE)
print("Dataset cache:", DATASET_CACHE)

# %%
# ============================================================
# Cell 2: Imports + GPU check
# ============================================================

import time
import json
import threading
import itertools
import gc

from dataclasses import dataclass, asdict
from typing import List, Dict, Optional

import torch
import numpy as np
import pandas as pd

from scipy import stats as scipy_stats

import logging

logging.getLogger("bitsandbytes").setLevel(logging.ERROR)

from pynvml import (
    nvmlInit,
    nvmlDeviceGetHandleByIndex,
    nvmlDeviceGetPowerUsage,
    nvmlDeviceGetName,
    nvmlDeviceGetUtilizationRates,
)

nvmlInit()

_handle = nvmlDeviceGetHandleByIndex(0)

gpu_name = nvmlDeviceGetName(_handle)

if isinstance(gpu_name, bytes):
    gpu_name = gpu_name.decode()

print("=" * 60)
print("GPU INFORMATION")
print("=" * 60)

print("GPU:", gpu_name)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("CUDA version:", torch.version.cuda)
    print("PyTorch version:", torch.__version__)
    print(
        "GPU memory:",
        round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2),
        "GB"
    )

print("=" * 60)


# Approximate theoretical peak FLOPs/s.
# Used only as a diagnostic, NOT as the main energy measurement.

PEAK_FLOPS_TABLE = {
    "Tesla T4": 65.13e12,
    "NVIDIA A100-SXM4-40GB": 312e12,
    "NVIDIA A100-SXM4-80GB": 312e12,
    "NVIDIA L4": 121e12,
}

# %%
# ============================================================
# Cell 3: GPU Power + Utilization Monitor
# ============================================================

class SystemMonitor:
    """
    Samples GPU power and utilization during one workload.

    Energy is estimated using trapezoidal integration:

        E = integral Power(t) dt

    Sampling interval:
        5 ms
    """

    def __init__(
        self,
        handle,
        pue: float = 1.10,
        sample_interval_s: float = 0.005,
    ):
        self.handle = handle
        self.pue = pue
        self.sample_interval_s = sample_interval_s

        self._power_samples = []
        self._util_samples = []

        self._stop_event = threading.Event()
        self._thread = None

    def _sample_loop(self):

        while not self._stop_event.is_set():

            t = time.perf_counter()

            try:

                power_w = (
                    nvmlDeviceGetPowerUsage(
                        self.handle
                    ) / 1000.0
                )

                utilization = (
                    nvmlDeviceGetUtilizationRates(
                        self.handle
                    ).gpu
                )

                self._power_samples.append(
                    (t, power_w)
                )

                self._util_samples.append(
                    utilization
                )

            except Exception:
                pass

            time.sleep(
                self.sample_interval_s
            )

    def __enter__(self):

        self._power_samples = []
        self._util_samples = []

        self._stop_event.clear()

        self._thread = threading.Thread(
            target=self._sample_loop,
            daemon=True,
        )

        self._thread.start()

        # Give sampler a tiny head start.
        time.sleep(
            self.sample_interval_s * 2
        )

        return self

    def __exit__(
        self,
        exc_type,
        exc_val,
        exc_tb,
    ):

        self._stop_event.set()

        if self._thread is not None:

            self._thread.join(
                timeout=2.0
            )

    def results(self):

        n_samples = len(
            self._power_samples
        )

        if n_samples < 3:

            raise RuntimeError(
                f"Only {n_samples} GPU power samples collected. "
                f"Increase max_new_tokens or reduce "
                f"sample_interval_s."
            )

        ts = np.array(
            [
                x[0]
                for x in self._power_samples
            ],
            dtype=float,
        )

        ws = np.array(
            [
                x[1]
                for x in self._power_samples
            ],
            dtype=float,
        )

        device_joules = float(
            np.trapezoid(
                ws,
                ts,
            )
        )

        duration_s = float(
            ts[-1] - ts[0]
        )

        avg_power = float(
            ws.mean()
        )

        avg_util = float(
            np.mean(
                self._util_samples
            )
        )

        return {
            "device_joules":
                device_joules,

            "facility_joules_estimate":
                device_joules * self.pue,

            "avg_device_power_w":
                avg_power,

            "avg_gpu_utilization_pct":
                avg_util,

            "duration_s":
                duration_s,

            "n_samples":
                n_samples,
        }



# %%
# ============================================================
# Cell 5: MMLU Quality Evaluation
# ============================================================

def load_quality_subset(
    n_samples=100,
    seed=42,
):

    from datasets import load_dataset

    ds = load_dataset(
        "cais/mmlu",
        "all",
        split="test",
        cache_dir=DATASET_CACHE,
    )

    ds = (
        ds
        .shuffle(seed=seed)
        .select(range(n_samples))
    )

    return [
        {
            "question": ex["question"],
            "choices": ex["choices"],
            "answer": ex["answer"],
        }
        for ex in ds
    ]


# Tiny smoke test.
MMLU_SMOKE_SUBSET = [

    {
        "question": "What is the capital of France?",
        "choices": [
            "Berlin",
            "Paris",
            "Madrid",
            "Rome"
        ],
        "answer": 1,
    },

    {
        "question": "Which planet is known as the Red Planet?",
        "choices": [
            "Venus",
            "Mars",
            "Jupiter",
            "Saturn"
        ],
        "answer": 1,
    },

    {
        "question": "What is 12 * 12?",
        "choices": [
            "144",
            "121",
            "132",
            "154"
        ],
        "answer": 0,
    },
]


LETTER_LABELS = ["A", "B", "C", "D"]


def format_mmlu_prompt(item):

    lines = [
        item["question"]
    ]

    for label, choice in zip(
        LETTER_LABELS,
        item["choices"]
    ):
        lines.append(
            f"{label}. {choice}"
        )

    lines.append("Answer:")

    return "\n".join(lines)


def evaluate_quality(
    model,
    tokenizer,
    subset,
):

    model.eval()

    letter_ids = []

    for letter in LETTER_LABELS:

        ids = tokenizer(
            " " + letter,
            add_special_tokens=False
        )["input_ids"]

        if len(ids) != 1:

            raise ValueError(
                f"Letter {letter} is not a single token: {ids}"
            )

        letter_ids.append(
            ids[0]
        )

    correct = 0

    for item in subset:

        prompt = format_mmlu_prompt(item)

        encoded = tokenizer(
            prompt,
            return_tensors="pt"
        )

        ids = encoded["input_ids"].to(
            model.device
        )

        with torch.no_grad():

            outputs = model(
                input_ids=ids
            )

        logits = outputs.logits[
            0,
            -1,
            :
        ]

        choice_logits = [
            logits[token_id].item()
            for token_id in letter_ids
        ]

        prediction = int(
            np.argmax(choice_logits)
        )

        correct += int(
            prediction == item["answer"]
        )

    return correct / len(subset)

# %%
# ============================================================
# Cell 6: Exact Context-Length Input
# ============================================================

def build_exact_length_input_ids(
    tokenizer,
    target_len,
    model_device,
    filler_text=(
        "The quick brown fox jumps over the lazy dog. "
    ),
):

    instruction = (
        " Given all of the above, explain the concept "
        "of gradient descent in machine learning."
    )

    instr_ids = tokenizer(
        instruction,
        return_tensors="pt"
    )["input_ids"]

    instr_len = instr_ids.shape[1]

    filler_ids = tokenizer(
        filler_text,
        return_tensors="pt"
    )["input_ids"][0]

    needed = target_len - instr_len

    if needed <= 0:

        raise ValueError(
            f"target_len={target_len} is too short."
        )

    repetitions = (
        needed // filler_ids.shape[0]
    ) + 1

    filler_repeated = (
        filler_ids
        .repeat(repetitions)
        [:needed]
    )

    full_ids = torch.cat(
        [
            filler_repeated,
            instr_ids[0],
        ]
    ).unsqueeze(0)

    full_ids = full_ids.to(
        model_device
    )

    assert full_ids.shape[1] == target_len

    return full_ids


CONTEXT_LENGTHS = {
    "short": 128,
    "medium": 768,
    "long": 1792,
}

# %%
# ============================================================
# Cell 7: Single-pass measurement (end-to-end energy)
# ============================================================

from dataclasses import dataclass, asdict

@dataclass
class RunResult:
    config_name: str
    total_joules: float
    total_facility_joules_est: float
    request_latency_s: float
    avg_device_power_w: float
    avg_gpu_utilization_pct: float
    num_input_tokens: int
    num_output_tokens: int
    batch_size: int
    peak_memory_mb: float
    n_power_samples: int


def measure_single_run(model, tokenizer, input_ids, config_name,
                        max_new_tokens=100, batch_size=1, pue=1.10):
    input_ids_batched = input_ids.repeat(batch_size, 1)
    attn_mask = torch.ones_like(input_ids_batched)
    pad_id = tokenizer.pad_token_id or tokenizer.eos_token_id
    input_len = input_ids_batched.shape[1]

    torch.cuda.reset_peak_memory_stats()
    torch.cuda.synchronize()
    mon = SystemMonitor(_handle, pue=pue, sample_interval_s=0.005)
    with mon:
        with torch.no_grad():
            output = model.generate(
                input_ids=input_ids_batched, attention_mask=attn_mask,
                max_new_tokens=max_new_tokens, do_sample=False, pad_token_id=pad_id,
            )
        torch.cuda.synchronize()
    m = mon.results()

    peak_mem_mb = torch.cuda.max_memory_allocated() / (1024 ** 2)
    total_output_len = output.shape[1] - input_len
    num_output_tokens = total_output_len * batch_size

    return RunResult(
        config_name=config_name,
        total_joules=m["device_joules"],
        total_facility_joules_est=m["facility_joules_estimate"],
        request_latency_s=m["duration_s"],
        avg_device_power_w=m["avg_device_power_w"],
        avg_gpu_utilization_pct=m["avg_gpu_utilization_pct"],
        num_input_tokens=input_len * batch_size,
        num_output_tokens=num_output_tokens,
        batch_size=batch_size,
        peak_memory_mb=peak_mem_mb,
        n_power_samples=m["n_samples"],
    )

# %%
# ============================================================
# Cell 8: Repeated Measurements + Statistics
# ============================================================

PUE_SWEEP = [
    1.1,
    1.2,
    1.4,
    1.6,
]


def run_with_repeats(
    model,
    tokenizer,
    input_ids,
    config_name,
    n_repeats=8,
    max_new_tokens=100,
    batch_size=1,
    pue=1.10,
    warmup_runs=2,
):

    # --------------------------------------------------------
    # Warmup
    # --------------------------------------------------------

    print(
        f"  Warmup: {warmup_runs} run(s)..."
    )

    for _ in range(warmup_runs):

        measure_single_run(

            model,
            tokenizer,
            input_ids,
            config_name,

            max_new_tokens=max_new_tokens,
            batch_size=batch_size,
            pue=pue,
        )

    rows = []

    # --------------------------------------------------------
    # Real measurements
    # --------------------------------------------------------

    for i in range(n_repeats):

        result = measure_single_run(

            model,
            tokenizer,
            input_ids,
            config_name,

            max_new_tokens=max_new_tokens,
            batch_size=batch_size,
            pue=pue,
        )

        d = asdict(result)

        # ----------------------------------------------------
        # PRIMARY METRIC
        # ----------------------------------------------------

        d["etok_total_j"] = (
            result.total_joules
            / result.num_output_tokens
        )

        # ----------------------------------------------------
        # Throughput
        # ----------------------------------------------------

        d["tokens_per_s"] = (
            result.num_output_tokens
            / result.request_latency_s
        )

        # ----------------------------------------------------
        # PUE sensitivity
        # ----------------------------------------------------

        for p in PUE_SWEEP:

            d[
                f"etok_total_facility_pue{p}"
            ] = (
                result.total_joules * p
            ) / result.num_output_tokens

        rows.append(d)

        print(
            f"  [{config_name}] "
            f"run {i+1}/{n_repeats}: "
            f"etok={d['etok_total_j']:.4f} J/tok | "
            f"tok/s={d['tokens_per_s']:.2f} | "
            f"power={d['avg_device_power_w']:.1f} W | "
            f"samples={d['n_power_samples']} | "
            f"mem={d['peak_memory_mb']:.0f} MB"
        )

    df = pd.DataFrame(rows)

    # --------------------------------------------------------
    # Outlier detection
    # --------------------------------------------------------

    median_energy = df[
        "etok_total_j"
    ].median()

    mad = (
        df["etok_total_j"]
        - median_energy
    ).abs().median()

    if mad > 0:

        df["is_outlier"] = (
            (
                df["etok_total_j"]
                - median_energy
            ).abs()
            > 3 * mad
        )

    else:

        df["is_outlier"] = False

    if df["is_outlier"].any():

        print(
            f"  WARNING: "
            f"{df['is_outlier'].sum()} "
            "outlier run(s) detected."
        )

    return df


def bootstrap_ci_median(
    values,
    n_boot=2000,
    ci=0.95,
    seed=0,
):

    rng = np.random.default_rng(
        seed
    )

    boot_medians = np.array([

        np.median(
            rng.choice(
                values,
                size=len(values),
                replace=True
            )
        )

        for _ in range(n_boot)

    ])

    alpha = 1 - ci

    lo, hi = np.percentile(
        boot_medians,
        [
            100 * alpha / 2,
            100 * (1 - alpha / 2)
        ]
    )

    return float(lo), float(hi)


def summarize(df):

    clean = df[
        ~df["is_outlier"]
    ].copy()

    if len(clean) == 0:

        raise RuntimeError(
            "All measurements were flagged as outliers."
        )

    energy = clean[
        "etok_total_j"
    ].values

    # Mean confidence interval
    if len(energy) > 1:

        ci_t = scipy_stats.t.interval(
            0.95,
            len(energy) - 1,
            loc=energy.mean(),
            scale=scipy_stats.sem(energy),
        )

    else:

        ci_t = (
            energy.mean(),
            energy.mean()
        )

    # Bootstrap median CI
    if len(energy) > 1:

        ci_boot = bootstrap_ci_median(
            energy
        )

    else:

        ci_boot = (
            energy[0],
            energy[0]
        )

    mean_energy = float(
        energy.mean()
    )

    std_energy = float(
        energy.std(ddof=1)
        if len(energy) > 1
        else 0
    )

    # Coefficient of variation
    cv_percent = (
        100 * std_energy / mean_energy
        if mean_energy > 0
        else np.nan
    )

    result = {

        "median":
            float(np.median(energy)),

        "mean":
            mean_energy,

        "std":
            std_energy,

        "cv_percent":
            float(cv_percent),

        "ci95_t_low":
            float(ci_t[0]),

        "ci95_t_high":
            float(ci_t[1]),

        "ci95_boot_low":
            float(ci_boot[0]),

        "ci95_boot_high":
            float(ci_boot[1]),

        "n":
            len(energy),

        "tokens_per_s_mean":
            float(
                clean[
                    "tokens_per_s"
                ].mean()
            ),

        "request_latency_mean_s":
            float(
                clean[
                    "request_latency_s"
                ].mean()
            ),

        "avg_power_mean_w":
            float(
                clean[
                    "avg_device_power_w"
                ].mean()
            ),

        "avg_gpu_utilization_mean_pct":
            float(
                clean[
                    "avg_gpu_utilization_pct"
                ].mean()
            ),

        "peak_memory_mean_mb":
            float(
                clean[
                    "peak_memory_mb"
                ].mean()
            ),

        "power_samples_mean":
            float(
                clean[
                    "n_power_samples"
                ].mean()
            ),
    }

    # PUE sensitivity
    for column in clean.columns:

        if column.startswith(
            "etok_total_facility_pue"
        ):

            result[
                f"{column}_mean"
            ] = float(
                clean[column].mean()
            )

    return result

# %%
# ============================================================
# Cell 9: PUE Ranking Robustness
# ============================================================

def check_pue_ranking_robustness(
    summary_df
):

    rankings = {}

    for p in PUE_SWEEP:

        column = (
            f"etok_total_facility_pue"
            f"{p}_mean"
        )

        if column not in summary_df.columns:

            print(
                f"Missing PUE column: {column}"
            )

            continue

        rankings[p] = list(
            summary_df
            .sort_values(column)
            ["config"]
        )

    if not rankings:

        print(
            "No PUE results available."
        )

        return None, {}

    base = rankings[
        list(rankings.keys())[0]
    ]

    stable = all(
        rankings[p] == base
        for p in rankings
    )

    print(
        "PUE ranking stable:",
        stable
    )

    if not stable:

        print(
            "*** WARNING: Configuration "
            "ranking changes with PUE assumption. "
            "Report this explicitly. ***"
        )

    return stable, rankings

# %%
# ============================================================
# Cell 10: Binding Constraint Diagnostic
# ============================================================

def binding_constraint_diagnostic(
    etok_j,
    avg_power_w,
    num_params,
    keff_flops_per_s,
    keff_label,
):

    ctok = (
        2 * num_params
    )

    rho = (
        avg_power_w
        / keff_flops_per_s
    )

    rho_star = (
        etok_j
        / ctok
    )

    constraint = (
        "Power-Limited"
        if rho < rho_star
        else "Compute-Limited"
    )

    return {

        "keff_type":
            keff_label,

        "ctok_flops_per_token":
            ctok,

        "rho_pj_per_flop":
            rho * 1e12,

        "rho_star_pj_per_flop":
            rho_star * 1e12,

        "constraint":
            constraint,
    }

# %%
# ============================================================
# Cell 10b: Microbenchmark Effective Throughput
# ============================================================

def measure_microbench_keff(
    dtype=torch.float16,
    matrix_size=2048,
    n_repeats=10,
):
    """
    Simple GPU GEMM microbenchmark.

    This measures an empirical compute-throughput proxy
    for the current GPU.

    It is NOT the model's inference throughput.
    """

    if not torch.cuda.is_available():

        raise RuntimeError(
            "CUDA GPU is required for the microbenchmark."
        )

    device = torch.device("cuda")

    A = torch.randn(
        matrix_size,
        matrix_size,
        device=device,
        dtype=dtype,
    )

    B = torch.randn(
        matrix_size,
        matrix_size,
        device=device,
        dtype=dtype,
    )

    # Warmup
    for _ in range(3):

        _ = torch.matmul(A, B)

    torch.cuda.synchronize()

    times = []

    for _ in range(n_repeats):

        start = torch.cuda.Event(
            enable_timing=True
        )

        end = torch.cuda.Event(
            enable_timing=True
        )

        start.record()

        _ = torch.matmul(A, B)

        end.record()

        torch.cuda.synchronize()

        elapsed_ms = (
            start.elapsed_time(end)
        )

        times.append(
            elapsed_ms / 1000.0
        )

    median_time_s = float(
        np.median(times)
    )

    # GEMM FLOPs ≈ 2 * N^3
    flops = (
        2
        * matrix_size
        * matrix_size
        * matrix_size
    )

    keff = (
        flops
        / median_time_s
    )

    del A, B

    torch.cuda.empty_cache()

    return float(keff)

# %%
# ============================================================
# Cell 10b: Effective Inference Throughput Proxy
# ============================================================

def effective_inference_throughput_proxy(
    flops_per_token,
    tokens_per_second,
):
    """
    Estimate effective inference compute throughput.

    flops_per_token:
        Approximate FLOPs required per generated token.

    tokens_per_second:
        Measured generation throughput.

    Returns:
        Effective FLOPs/s.
    """

    return float(
        flops_per_token
        * tokens_per_second
    )

# %%
# ============================================================
# Cell 11: Model Loading
# ============================================================

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
)


MODEL_NAME = (
    "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
)

MODEL_NUM_PARAMS = 1.1e9


def load_model(
    precision,
    attn_impl="eager",
):

    print(
        f"\nLoading model: "
        f"precision={precision}, "
        f"attention={attn_impl}"
    )

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME,
        cache_dir=HF_CACHE,
    )

    if tokenizer.pad_token is None:

        tokenizer.pad_token = (
            tokenizer.eos_token
        )

    kwargs = {

        "device_map": "cuda",

        "attn_implementation":
            attn_impl,

    }

    # --------------------------------------------------------
    # FP16
    # --------------------------------------------------------

    if precision == "fp16":

        kwargs["dtype"] = torch.float16

    # --------------------------------------------------------
    # INT8
    # --------------------------------------------------------

    elif precision == "int8":

        kwargs[
            "quantization_config"
        ] = BitsAndBytesConfig(
            load_in_8bit=True
        )

    # --------------------------------------------------------
    # INT4
    # --------------------------------------------------------

    elif precision == "int4":

        kwargs[
            "quantization_config"
        ] = BitsAndBytesConfig(

            load_in_4bit=True,

            bnb_4bit_compute_dtype=
                torch.float16,

            bnb_4bit_quant_type=
                "nf4",
        )

    else:

        raise ValueError(
            f"Unknown precision: {precision}"
        )

    try:

        model = (
            AutoModelForCausalLM
            .from_pretrained(
                MODEL_NAME,
                cache_dir=HF_CACHE,
                **kwargs,
            )
        )

    except Exception as e:

        print(
            "*** Model loading failed "
            "with requested attention implementation. "
            "Falling back to eager. ***"
        )

        print("Error:", e)

        kwargs[
            "attn_implementation"
        ] = "eager"

        model = (
            AutoModelForCausalLM
            .from_pretrained(
                MODEL_NAME,
                cache_dir=HF_CACHE,
                **kwargs,
            )
        )

    model.eval()

    actual_impl = getattr(
        model.config,
        "_attn_implementation",
        "unknown"
    )

    print(
        "Actual attention implementation:",
        actual_impl
    )

    return model, tokenizer

# %%
# ============================================================
# Cell 12: Checkpointing + Experiment Sweep
# ============================================================

CHECKPOINT_CSV = "etok_context_1792_final.csv"


def load_completed_configs(path):
    if not os.path.exists(path):
        return set()
    try:
        df = pd.read_csv(path)
        if "config" not in df.columns:
            return set()
        return set(df["config"].tolist())
    except Exception:
        return set()


def flatten_result_row(config_name, result):
    row = {
        "config": config_name,
        **result["summary"],
        "quality_accuracy": result["quality_accuracy"],
        "peak_memory_mb": result["peak_memory_mb"],
        "avg_gpu_utilization_pct": result["avg_gpu_utilization_pct"],
        "avg_request_latency_s": result["avg_request_latency_s"],
        "context_tokens": result["context_tokens"],
        "batch_size": result["batch_size"],
        "precision": result["precision"],
    }
    for tier, diagnostic in result["diagnostics"].items():
        row.update({f"{tier}_{key}": value for key, value in diagnostic.items()})
    return row


def append_checkpoint(config_name, result, path=CHECKPOINT_CSV):
    if os.path.exists(path):
        existing = pd.read_csv(path)
    else:
        existing = pd.DataFrame()

    new_row = pd.DataFrame([flatten_result_row(config_name, result)])

    if len(existing):
        existing = existing[existing["config"] != config_name]
        combined = pd.concat([existing, new_row], ignore_index=True)
    else:
        combined = new_row

    combined.to_csv(path, index=False)
    print(f"[checkpoint] {config_name} saved -> {path} ({len(combined)} configs)")


def run_experiment_sweep(
    precisions=("fp16", "int8", "int4"),
    batch_sizes=(1, 8),
    attn_impls=("eager",),
    context_lengths=CONTEXT_LENGTHS,
    n_repeats=8,
    max_new_tokens=100,
    pue_estimate=1.10,
    num_params=MODEL_NUM_PARAMS,
    quality_subset=None,
    checkpoint_path=CHECKPOINT_CSV,
):
    if quality_subset is None:
        quality_subset = MMLU_SMOKE_SUBSET
        print("*** WARNING: Using 3-question smoke test. "
              "Use 100 questions for the real experiment. ***")

    completed = load_completed_configs(checkpoint_path)
    if completed:
        print(f"Resuming: {len(completed)} configuration(s) already done.")

    all_results = {}

    # ========================================================
    # Precision × Attention
    # ========================================================
    for precision, attn_impl in itertools.product(precisions, attn_impls):

        print("\n" + "=" * 70)
        print(f"MODEL: precision={precision}, attention={attn_impl}")
        print("=" * 70)

        model, tokenizer = load_model(precision, attn_impl)

        microbench_keff = measure_microbench_keff(dtype=torch.float16)
        print(f"Microbenchmark Keff: {microbench_keff / 1e12:.2f} TFLOPs/s")

        quality = evaluate_quality(model, tokenizer, quality_subset)
        print(f"Quality accuracy: {quality:.2%} (n={len(quality_subset)})")

        # ====================================================
        # Batch × Context
        # ====================================================
        for batch_size, (ctx_name, ctx_len) in itertools.product(batch_sizes, context_lengths.items()):

            config_name = f"{precision}_{attn_impl}_batch{batch_size}_{ctx_name}"

            if config_name in completed:
                print(f"\nSKIPPING: {config_name}")
                continue

            print("\n" + "-" * 70)
            print(f"CONFIG: {config_name}")
            print("-" * 70)

            input_ids = build_exact_length_input_ids(tokenizer, ctx_len, model.device)
            print("Input context tokens:", input_ids.shape[1])

            # ------------------------------------------------
            # Reduce max_new_tokens for large batch + long
            # context, to lower OOM risk before we even try.
            # ------------------------------------------------
            effective_max_new_tokens = max_new_tokens
            if batch_size >= 8 and ctx_len >= 1000:
                effective_max_new_tokens = 30
                print(f"  (reduced max_new_tokens to {effective_max_new_tokens} "
                      f"for large batch+context)")

            # ------------------------------------------------
            # Measurements -- OOM-safe: log and skip, don't crash
            # ------------------------------------------------
            try:
                raw_df = run_with_repeats(
                    model, tokenizer, input_ids, config_name,
                    n_repeats=n_repeats, max_new_tokens=effective_max_new_tokens,
                    batch_size=batch_size, pue=pue_estimate,
                )
            except torch.cuda.OutOfMemoryError:
                print(f"  *** OOM on {config_name} (batch={batch_size}, ctx={ctx_len}) -- SKIPPING ***")
                torch.cuda.empty_cache()
                gc.collect()
                oom_log_entry = {
                    "config": config_name, "status": "OOM",
                    "batch_size": batch_size, "context_tokens": ctx_len, "precision": precision,
                }
                oom_path = "etok_oom_log.csv"
                existing_oom = pd.read_csv(oom_path) if os.path.exists(oom_path) else pd.DataFrame()
                pd.concat([existing_oom, pd.DataFrame([oom_log_entry])],
                          ignore_index=True).to_csv(oom_path, index=False)
                continue  # next config, sweep keeps going

            # ------------------------------------------------
            # Summary
            # ------------------------------------------------
            summary = summarize(raw_df)

            print("\nSummary:")
            print(f"Median J/token: {summary['median']:.4f}")
            print(f"Mean J/token: {summary['mean']:.4f}")
            print(f"CV: {summary['cv_percent']:.2f}%")
            print(f"Tokens/s: {summary['tokens_per_s_mean']:.2f}")
            print(f"Average power: {summary['avg_power_mean_w']:.2f} W")
            print(f"Average power samples: {summary['power_samples_mean']:.1f}")

            effective_throughput = effective_inference_throughput_proxy(
                2 * num_params, summary["tokens_per_s_mean"])

            avg_power = summary["avg_power_mean_w"]

            diagnostics = {
                "microbench": binding_constraint_diagnostic(
                    summary["median"], avg_power, int(num_params),
                    microbench_keff, "microbenchmark"),
                "effective_throughput_proxy": binding_constraint_diagnostic(
                    summary["median"], avg_power, int(num_params),
                    effective_throughput, "effective_throughput_proxy"),
            }

            peak_keff = PEAK_FLOPS_TABLE.get(gpu_name)
            if peak_keff:
                diagnostics["peak"] = binding_constraint_diagnostic(
                    summary["median"], avg_power, int(num_params), peak_keff, "peak")

            result_entry = {
                "raw_df": raw_df,
                "summary": summary,
                "quality_accuracy": quality,
                "peak_memory_mb": summary["peak_memory_mean_mb"],
                "avg_gpu_utilization_pct": summary["avg_gpu_utilization_mean_pct"],
                "avg_request_latency_s": summary["request_latency_mean_s"],
                "context_tokens": ctx_len,
                "batch_size": batch_size,
                "precision": precision,
                "diagnostics": diagnostics,
                "microbench_keff_flops_s": microbench_keff,
                "effective_throughput_proxy_flops_s": effective_throughput,
            }

            all_results[config_name] = result_entry

            append_checkpoint(config_name, result_entry, checkpoint_path)

        del model
        gc.collect()
        torch.cuda.empty_cache()
        print(f"\nFinished precision={precision}")

    return all_results

# %%
# ============================================================
# Cell 13: Feasibility Analysis
# ============================================================

def feasibility_analysis(

    summary_df,

    baseline_config,

    quality_epsilon=0.02,

    latency_slo_s=None,
):

    base = summary_df[
        summary_df["config"]
        == baseline_config
    ]

    if len(base) == 0:

        print(
            f"Baseline not found: "
            f"{baseline_config}"
        )

        return pd.DataFrame()

    baseline_quality = (
        base.iloc[0][
            "quality_accuracy"
        ]
    )

    rows = []

    for _, row in summary_df.iterrows():

        quality_ok = (
            row["quality_accuracy"]
            >=
            baseline_quality
            - quality_epsilon
        )

        if latency_slo_s is None:

            latency_ok = True

        else:

            latency_ok = (
                row[
                    "avg_request_latency_s"
                ]
                <= latency_slo_s
            )

        rows.append({

            "config":
                row["config"],

            "energy_j_per_token":
                row["median"],

            "quality_accuracy":
                row["quality_accuracy"],

            "latency_s":
                row[
                    "avg_request_latency_s"
                ],

            "quality_feasible":
                quality_ok,

            "latency_feasible":
                latency_ok,

            "feasible":
                quality_ok
                and latency_ok,
        })

    result = pd.DataFrame(
        rows
    ).sort_values(
        "energy_j_per_token"
    )

    feasible = result[
        result["feasible"]
    ]

    if len(feasible):

        best = feasible.iloc[0]

        print(
            "\nBest feasible configuration:"
        )

        print(
            best["config"]
        )

        print(
            f"Energy: "
            f"{best['energy_j_per_token']:.4f} J/token"
        )

        print(
            f"Quality: "
            f"{best['quality_accuracy']:.2%}"
        )

    else:

        print(
            "No configuration meets "
            "the feasibility constraints."
        )

    return result

context_lengths=CONTEXT_LENGTHS,

print(measure_single_run)
print(run_with_repeats)
print(run_experiment_sweep)

# %%
# ============================================================
# Cell 14: RUN EXPERIMENT
# ============================================================

RUN_FULL_SWEEP = True


if RUN_FULL_SWEEP:

    # ========================================================
    # REAL EXPERIMENT
    # ========================================================

    quality_subset = load_quality_subset(
        n_samples=100,
        seed=42,
    )

    results = run_experiment_sweep(

        precisions=(
            "fp16",
            "int8",
            "int4",
        ),

        attn_impls=(
            "eager",
        ),

        batch_sizes=(
            1,
            4,
            8,
            16,
        ),

        context_lengths=CONTEXT_LENGTHS,

        n_repeats=8,

        max_new_tokens=100,

        quality_subset=quality_subset,

        checkpoint_path=CHECKPOINT_CSV,
    )

    active_checkpoint = CHECKPOINT_CSV


else:

    # ========================================================
    # SMOKE TEST
    # ========================================================

    print("*** RUNNING SMOKE TEST ***")

    SMOKE_CHECKPOINT = "etok_context_1792.csv"

    quality_subset = MMLU_SMOKE_SUBSET

    results = run_experiment_sweep(
        precisions=("fp16", "int8", "int4"),
        attn_impls=("eager",),
        batch_sizes=(1, 8),
        context_lengths=CONTEXT_LENGTHS,
        n_repeats=8,
        max_new_tokens=100,
        quality_subset=quality_subset,
        checkpoint_path=SMOKE_CHECKPOINT,
    )

    active_checkpoint = SMOKE_CHECKPOINT


# ============================================================
# Load results
# ============================================================

summary_df = pd.read_csv(active_checkpoint)

print("\n" + "=" * 70)
print("CURRENT RESULTS")
print("=" * 70)

print(
    summary_df[
        ["config", "median", "mean", "cv_percent", "quality_accuracy",
         "tokens_per_s_mean", "avg_power_mean_w", "peak_memory_mean_mb",
         "power_samples_mean"]
    ].to_string(index=False)
)

check_pue_ranking_robustness(summary_df)

baseline = "fp16_eager_batch1_short"
if baseline in summary_df["config"].values:
    feasibility_df = feasibility_analysis(
        summary_df, baseline_config=baseline,
        quality_epsilon=0.02, latency_slo_s=None,
    )
    feasibility_df.to_csv("etok_feasibility_analysis_context_1792.csv", index=False)
    print("\nSaved feasibility analysis.")
else:
    print("\nBaseline not completed yet.")

import pandas as pd
df = pd.read_csv("etok_context_1792_final.csv")
print(f"عدد الصفوف: {len(df)}")
print(df[["config", "median", "quality_accuracy"]].to_string(index=False))

